AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: JVM Template Lambda Functions

Parameters:
  DevSuffix:
    Type: String
    Default: ''

Resources:
  GetGearListHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName:
        !Join
          - ""
          - - Caampr-GetGearList
            - !Ref DevSuffix
      Handler: com.jelistan.caampr.lambda.dagger.InvocationHandlers::handleGetGearListRequest
      Runtime: java8
      Description: Java Lambda Function
      MemorySize: 512
      Timeout: 300
      CodeUri: ../build/distributions/caampr-backend-1.0-SNAPSHOT.zip
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          ROLE_NAME: !Ref LambdaRole
          ACCOUNT_ID: !Ref AWS::AccountId
          REGION: !Ref AWS::Region

  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        !Join
          - ""
          - - LambdaRole
            - !Ref DevSuffix
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName:
            !Join
              - ""
              - - allow-lambda-to-use-logs-policy
                - !Ref DevSuffix
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"